### ISSUE TITLE
deploy script is wrong

### ISSUE THREAD

**Issue by osaguild** [osaguild/saitama-premium#35]
- can not deploy from deploy script
- need to deploy from local
- error message when using deploy script
- ```
  Traceback (most recent call last):
    File "/Users/nobuhisaabe/Documents/MyApps/saitama-premium/app.py", line 1, in <module>
      from aws_cdk import (
    File "/usr/local/lib/python3.9/site-packages/aws_cdk/__init__.py", line 1054, in <module>
      from .cloud_assembly_schema import (
  ImportError: cannot import name 'BootstrapRole' from 'aws_cdk.cloud_assembly_schema' (/usr/local/lib/python3.9/site-packages/aws_cdk/cloud_assembly_schema/__init__.py)
  Subprocess exited with error 1
  ```

**Comment by osaguild** [comment]
include in #42
